name: Spack buildcache build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rebuild:
    timeout-minutes: 180
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Spack
      uses: spack/setup-spack@v2

    - name: Spack version
      run: spack debug report

    - name: Set authentication method for mirror
      if: ${{ github.event_name == 'push' }}
      run: spack -e . mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" local-buildcache

    - name: Concretize
      run: spack -e . concretize

    - name: Install
      timeout-minutes: 300
      run: |
        spack -e . env depfile -o Makefile
        make -Orecurse -j $(($(nproc) + 1))

    - name: Push packages and update index
      run: |
        spack -e . buildcache push -j $(($(nproc) + 1)) --base-image ubuntu:22.04 --update-index local-buildcache
        # Build containers with two top-level specs
        spack -e . buildcache push -j $(($(nproc) + 1)) --base-image ubuntu:22.04 --tag intel-mpi-jq --update-index local-buildcache jq@1.7.1 intel-mpi@2019.9.304
        spack -e . buildcache push -j $(($(nproc) + 1)) --base-image ubuntu:22.04 --tag intel-oneapi-mpi-jq --update-index local-buildcache jq@1.7.1 intel-oneapi-mpi@2021.11.0
        spack -e . buildcache push -j $(($(nproc) + 1)) --base-image ubuntu:22.04 --tag mvapich2-jq --update-index local-buildcache jq@1.7.1 jq@1.7.1 mvapich2@2.3.7
        spack -e . buildcache push -j $(($(nproc) + 1)) --base-image ubuntu:22.04 --tag mvapich3-jq --update-index local-buildcache jq@1.7.1 jq@1.7.1 mvapich@3.0b
      if: ${{ !cancelled() }}
